"""
PDF export module for EquiLens.
Generates a clean equity research report using fpdf2.
"""

from fpdf import FPDF
import pandas as pd
import tempfile
import os


class EquiLensPDF(FPDF):
    """Custom PDF class with branded header and footer."""

    def __init__(self, company_name: str, ticker: str):
        super().__init__()
        self.company_name = company_name
        self.ticker = ticker

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, f"EquiLens Research Report | {self.company_name} ({self.ticker})", align="L")
        self.ln(10)
        self.set_draw_color(0, 212, 170)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | Generated by EquiLens", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(0, 0, 0)
        self.ln(5)
        self.cell(0, 10, title)
        self.ln(8)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, text)
        self.ln(3)

    def add_ratio_table(self, title: str, df: pd.DataFrame):
        """Add a ratio table to the PDF."""
        self.section_title(title)

        if df.empty:
            self.body_text("No data available.")
            return

        # Table header
        self.set_font("Helvetica", "B", 9)
        self.set_fill_color(0, 212, 170)
        self.set_text_color(255, 255, 255)

        col_width = 180 / (len(df.columns) + 1)
        self.cell(col_width + 20, 7, "Metric", border=1, fill=True, align="C")
        for col in df.columns:
            self.cell(col_width, 7, str(col), border=1, fill=True, align="C")
        self.ln()

        # Table rows
        self.set_font("Helvetica", "", 9)
        self.set_text_color(50, 50, 50)

        for idx in df.index:
            self.cell(col_width + 20, 6, str(idx)[:25], border=1, align="L")
            for col in df.columns:
                val = df.loc[idx, col]
                if isinstance(val, (int, float)):
                    text = f"{val:.2f}"
                else:
                    text = str(val)
                self.cell(col_width, 6, text, border=1, align="C")
            self.ln()

        self.ln(5)


def generate_pdf(
    company_name: str,
    ticker: str,
    stock_info: dict,
    all_ratios: dict,
    health_score: int,
    dcf_result: dict,
    scenarios: dict,
    narrative: str,
    z_score: float,
    z_zone: str,
    ddm_result: dict = None,
    comps_result: dict = None,
) -> str:
    """
    Generate a full equity research PDF report.
    Returns the path to the generated temporary PDF file.
    """
    pdf = EquiLensPDF(company_name, ticker)
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title page info
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 15, company_name, align="C")
    pdf.ln(12)
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Ticker: {ticker} | Sector: {stock_info.get('sector', 'N/A')}", align="C")
    pdf.ln(5)
    pdf.cell(0, 8, f"CMP: INR {stock_info.get('cmp', 0):,.2f} | Market Cap: INR {stock_info.get('market_cap', 0)/1e7:,.0f} Cr", align="C")
    pdf.ln(12)

    # Health Score
    hs_display = health_score if isinstance(health_score, (int, float)) else health_score.get("score", 0)
    hs_grade = health_score.get("grade", "") if isinstance(health_score, dict) else ""
    grade_str = f" (Grade: {hs_grade})" if hs_grade else ""
    pdf.section_title(f"Financial Health Score: {hs_display}/100{grade_str}")
    pdf.body_text(f"Altman Z-Score: {z_score} ({z_zone} Zone)")
    pdf.ln(3)

    # Narrative
    pdf.section_title("Investment Summary")
    # Clean markdown formatting for PDF
    clean_narrative = narrative.replace("**", "").replace("*", "")
    pdf.body_text(clean_narrative)

    # DCF Valuation
    pdf.add_page()
    pdf.section_title("DCF Valuation")
    if dcf_result:
        pdf.body_text(f"Intrinsic Value per Share: INR {dcf_result.get('intrinsic_per_share', 0):,.2f}")
        pdf.body_text(f"Enterprise Value: INR {dcf_result.get('enterprise_value', 0)/1e7:,.0f} Cr")

    if scenarios:
        pdf.body_text(f"Bear Case: INR {scenarios.get('Bear', 0):,.2f}")
        pdf.body_text(f"Base Case: INR {scenarios.get('Base', 0):,.2f}")
        pdf.body_text(f"Bull Case: INR {scenarios.get('Bull', 0):,.2f}")

    # DDM
    if ddm_result and ddm_result.get("applicable"):
        pdf.ln(5)
        pdf.section_title("Dividend Discount Model (DDM)")
        pdf.body_text(f"DDM Intrinsic Value: INR {ddm_result['intrinsic_per_share']:,.2f}")
        pdf.body_text(f"High Growth Phase: {ddm_result['high_growth_rate']*100:.1f}% for 5 years")
        pdf.body_text(f"Terminal Growth: {ddm_result['terminal_growth']*100:.1f}%")

    # Comparable Valuation
    if comps_result:
        pe = comps_result.get("pe_comps", {})
        ev = comps_result.get("ev_ebitda_comps", {})
        if pe.get("applicable") or ev.get("applicable"):
            pdf.ln(5)
            pdf.section_title("Comparable Valuation")
            if pe.get("applicable"):
                pdf.body_text(f"PE Comps Fair Value: INR {pe['fair_value_median']:,.2f} (Median PE: {pe['peer_median_pe']:.1f}x)")
                pdf.body_text(f"  Range: INR {pe['fair_value_low']:,.2f} - INR {pe['fair_value_high']:,.2f}")
            if ev.get("applicable"):
                pdf.body_text(f"EV/EBITDA Fair Value: INR {ev['fair_value_median']:,.2f} (Median: {ev['peer_median_multiple']:.1f}x)")
                pdf.body_text(f"  Range: INR {ev['fair_value_low']:,.2f} - INR {ev['fair_value_high']:,.2f}")

    # Ratio tables
    for category, df in all_ratios.items():
        if isinstance(df, pd.DataFrame) and not df.empty:
            pdf.add_page()
            title_map = {
                "profitability": "Profitability Ratios",
                "liquidity": "Liquidity Ratios",
                "efficiency": "Efficiency Ratios",
                "solvency": "Solvency Ratios",
                "dupont": "DuPont Decomposition",
                "altman": "Altman Z-Score Components",
            }
            pdf.add_ratio_table(title_map.get(category, category.title()), df)

    # Disclaimer
    pdf.add_page()
    pdf.section_title("Disclaimer")
    pdf.body_text(
        "This report is generated automatically by EquiLens for educational and informational purposes only. "
        "It does not constitute investment advice. Always consult a SEBI-registered investment advisor "
        "before making investment decisions. Past performance is not indicative of future results. "
        "The data used in this report is sourced from public APIs and may contain errors or delays."
    )

    # Save to temp file
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf", prefix=f"EquiLens_{ticker}_")
    pdf.output(tmp.name)
    return tmp.name
