"""
PDF export module for EquiLens.
Generates a clean equity research report using fpdf2 with Unicode support
and embedded matplotlib charts.
"""

from fpdf import FPDF
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import tempfile
import os

# Page geometry (A4)
PAGE_W = 210
MARGIN_L = 15
MARGIN_R = 15
USABLE_W = PAGE_W - MARGIN_L - MARGIN_R  # 180mm

# Chart style constants
CHART_BG = "#1A1D2E"
CHART_FG = "#FAFAFA"
ACCENT = "#00D4AA"
RED = "#FF6B6B"
AMBER = "#FFE66D"
BLUE = "#4ECDC4"
PURPLE = "#A78BFA"
PINK = "#F472B6"


def _chart_style():
    """Apply consistent dark theme to matplotlib figures."""
    plt.rcParams.update({
        "figure.facecolor": CHART_BG,
        "axes.facecolor": CHART_BG,
        "axes.edgecolor": "#3D4260",
        "axes.labelcolor": CHART_FG,
        "xtick.color": CHART_FG,
        "ytick.color": CHART_FG,
        "text.color": CHART_FG,
        "grid.color": "#2D3250",
        "grid.alpha": 0.5,
        "font.size": 9,
        "legend.facecolor": CHART_BG,
        "legend.edgecolor": "#3D4260",
    })


def _save_chart(fig) -> str:
    """Save a matplotlib figure to a temp PNG and return the path."""
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".png", prefix="equilens_chart_")
    fig.savefig(tmp.name, dpi=180, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close(fig)
    return tmp.name


class EquiLensPDF(FPDF):
    """Custom PDF class with branded header and footer, Unicode font."""

    def __init__(self, company_name: str, ticker: str):
        super().__init__()
        self.company_name = company_name
        self.ticker = ticker
        self.set_left_margin(MARGIN_L)
        self.set_right_margin(MARGIN_R)
        self._setup_fonts()
        self._chart_files = []

    def _setup_fonts(self):
        font_dir = "C:/Windows/Fonts"
        if os.path.exists(f"{font_dir}/arial.ttf"):
            self.add_font("ArialUni", "", f"{font_dir}/arial.ttf")
            self.add_font("ArialUni", "B", f"{font_dir}/arialbd.ttf")
            self.add_font("ArialUni", "I", f"{font_dir}/ariali.ttf")
        else:
            font_dir = os.path.join(os.path.dirname(__file__), "fonts")
            if os.path.exists(os.path.join(font_dir, "DejaVuSans.ttf")):
                self.add_font("ArialUni", "", os.path.join(font_dir, "DejaVuSans.ttf"))
                self.add_font("ArialUni", "B", os.path.join(font_dir, "DejaVuSans-Bold.ttf"))
                self.add_font("ArialUni", "I", os.path.join(font_dir, "DejaVuSans-Oblique.ttf"))
            else:
                self.add_font("ArialUni", "", os.path.join("/usr/share/fonts/truetype/dejavu", "DejaVuSans.ttf"))
                self.add_font("ArialUni", "B", os.path.join("/usr/share/fonts/truetype/dejavu", "DejaVuSans-Bold.ttf"))
                self.add_font("ArialUni", "I", os.path.join("/usr/share/fonts/truetype/dejavu", "DejaVuSans-Oblique.ttf"))

    def cleanup(self):
        for f in self._chart_files:
            try:
                os.unlink(f)
            except OSError:
                pass

    def header(self):
        self.set_font("ArialUni", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, f"EquiLens Research Report | {self.company_name} ({self.ticker})", align="L")
        self.ln(10)
        self.set_draw_color(0, 212, 170)
        self.line(MARGIN_L, self.get_y(), PAGE_W - MARGIN_R, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("ArialUni", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | Generated by EquiLens", align="C")

    def section_title(self, title: str):
        self.set_font("ArialUni", "B", 14)
        self.set_text_color(0, 0, 0)
        self.ln(5)
        self.cell(0, 10, title)
        self.ln(8)

    def sub_title(self, title: str):
        self.set_font("ArialUni", "B", 11)
        self.set_text_color(50, 50, 50)
        self.ln(3)
        self.cell(0, 8, title)
        self.ln(6)

    def body_text(self, text: str):
        self.set_font("ArialUni", "", 10)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, text)
        self.ln(3)

    def key_value(self, label: str, value: str):
        self.set_font("ArialUni", "B", 10)
        self.set_text_color(80, 80, 80)
        self.cell(65, 6, label, align="L")
        self.set_font("ArialUni", "", 10)
        self.set_text_color(30, 30, 30)
        self.cell(0, 6, value, align="L")
        self.ln(7)

    def add_chart(self, img_path: str, w: float = None):
        """Embed a chart image, centered on the page."""
        self._chart_files.append(img_path)
        if w is None:
            w = USABLE_W
        x = MARGIN_L + (USABLE_W - w) / 2
        if self.get_y() + 80 > self.h - 25:
            self.add_page()
        self.image(img_path, x=x, w=w)
        self.ln(5)

    def add_ratio_table(self, title: str, df: pd.DataFrame):
        self.section_title(title)
        if df.empty:
            self.body_text("No data available.")
            return

        n_data_cols = len(df.columns)
        first_col_w = 42
        data_col_w = (USABLE_W - first_col_w) / max(n_data_cols, 1)

        self.set_font("ArialUni", "B", 8)
        self.set_fill_color(0, 212, 170)
        self.set_text_color(255, 255, 255)

        self.cell(first_col_w, 7, "Metric", border=1, fill=True, align="C")
        for col in df.columns:
            self.cell(data_col_w, 7, str(col), border=1, fill=True, align="C")
        self.ln()

        self.set_font("ArialUni", "", 8)
        self.set_text_color(50, 50, 50)

        for i, idx in enumerate(df.index):
            if i % 2 == 0:
                self.set_fill_color(245, 245, 245)
            else:
                self.set_fill_color(255, 255, 255)

            self.cell(first_col_w, 6, str(idx)[:28], border=1, align="L", fill=True)
            for col in df.columns:
                val = df.loc[idx, col]
                if isinstance(val, (int, float)):
                    text = f"{val:.2f}"
                else:
                    text = str(val)
                self.cell(data_col_w, 6, text, border=1, align="C", fill=True)
            self.ln()

        self.ln(5)

    def add_simple_table(self, headers: list, rows: list):
        n_cols = len(headers)
        col_width = USABLE_W / n_cols

        self.set_font("ArialUni", "B", 9)
        self.set_fill_color(0, 212, 170)
        self.set_text_color(255, 255, 255)
        for h in headers:
            self.cell(col_width, 7, str(h), border=1, fill=True, align="C")
        self.ln()

        self.set_font("ArialUni", "", 9)
        self.set_text_color(50, 50, 50)
        for i, row in enumerate(rows):
            if i % 2 == 0:
                self.set_fill_color(245, 245, 245)
            else:
                self.set_fill_color(255, 255, 255)
            for val in row:
                self.cell(col_width, 6, str(val), border=1, align="C", fill=True)
            self.ln()
        self.ln(3)


# ── Chart generators (matplotlib) ──────────────────────────────────

def _make_health_gauge(score, grade=""):
    _chart_style()
    fig, ax = plt.subplots(figsize=(5, 2.8), subplot_kw={"projection": "polar"})
    fig.set_facecolor(CHART_BG)
    ax.set_facecolor(CHART_BG)

    theta_range = np.pi
    zones = [(0, 40, RED), (40, 70, AMBER), (70, 100, ACCENT)]
    for lo, hi, color in zones:
        start = np.pi - (lo / 100) * theta_range
        end = np.pi - (hi / 100) * theta_range
        theta = np.linspace(start, end, 50)
        ax.fill_between(theta, 0.6, 1.0, color=color, alpha=0.25)

    needle_angle = np.pi - (score / 100) * theta_range
    ax.plot([needle_angle, needle_angle], [0, 0.95], color=ACCENT, linewidth=3)
    ax.scatter([needle_angle], [0.95], color=ACCENT, s=40, zorder=5)

    ax.set_ylim(0, 1.2)
    ax.set_thetamin(0)
    ax.set_thetamax(180)
    ax.set_axis_off()

    label = f"Health Score: {score}/100"
    if grade:
        label += f"  (Grade: {grade})"
    ax.text(np.pi / 2, -0.3, label, ha="center", va="center",
            fontsize=14, fontweight="bold", color=CHART_FG, transform=ax.transAxes)

    return _save_chart(fig)


def _make_scenario_chart(scenarios, cmp):
    _chart_style()
    fig, ax = plt.subplots(figsize=(6, 3))

    names = list(scenarios.keys())
    values = list(scenarios.values())
    colors_map = {"Bear": RED, "Base": AMBER, "Bull": ACCENT}
    colors = [colors_map.get(n, BLUE) for n in names]

    bars = ax.barh(names, values, color=colors, height=0.5, edgecolor="#3D4260")
    for bar, val in zip(bars, values):
        upside = ((val - cmp) / cmp * 100) if cmp > 0 else 0
        ax.text(bar.get_width() + cmp * 0.02, bar.get_y() + bar.get_height() / 2,
                f"₹{val:,.0f} ({upside:+.1f}%)", va="center", fontsize=8, color=CHART_FG)

    ax.axvline(x=cmp, color=RED, linestyle="--", linewidth=1.5, label=f"CMP: ₹{cmp:,.0f}")
    ax.legend(loc="lower right", fontsize=8)
    ax.set_xlabel("Price (₹)", fontsize=9)
    ax.set_title("Scenario Analysis", fontsize=12, fontweight="bold", color=CHART_FG)
    ax.grid(axis="x", alpha=0.3)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    return _save_chart(fig)


def _make_shareholding_chart(shareholding):
    _chart_style()
    labels = []
    sizes = []
    for k, v in shareholding.items():
        if v > 0:
            labels.append(k)
            sizes.append(v)

    if not sizes:
        return None

    colors = [ACCENT, PURPLE, BLUE, AMBER, PINK, RED][:len(labels)]

    fig, ax = plt.subplots(figsize=(4.5, 3.5))
    wedges, texts, autotexts = ax.pie(
        sizes, labels=labels, autopct="%1.1f%%", startangle=90,
        colors=colors, pctdistance=0.8, wedgeprops=dict(width=0.45, edgecolor=CHART_BG),
        textprops=dict(color=CHART_FG, fontsize=8),
    )
    for t in autotexts:
        t.set_fontsize(7)
        t.set_color(CHART_FG)

    ax.set_title("Shareholding Pattern", fontsize=12, fontweight="bold", color=CHART_FG, pad=10)

    return _save_chart(fig)


def _make_returns_chart(hist_returns, ticker):
    _chart_style()
    periods = []
    stock_vals = []
    bench_vals = []

    for period in ["1Y", "3Y", "5Y"]:
        data = hist_returns.get(period, {})
        s = data.get("stock")
        if s is not None:
            periods.append(period)
            stock_vals.append(s)
            bench_vals.append(data.get("benchmark", 0) or 0)

    if not periods:
        return None

    fig, ax = plt.subplots(figsize=(5, 3))
    x = np.arange(len(periods))
    w = 0.35

    bars1 = ax.bar(x - w / 2, stock_vals, w, color=ACCENT, label=ticker.replace(".NS", ""), edgecolor="#3D4260")
    bars2 = ax.bar(x + w / 2, bench_vals, w, color=BLUE, label="Nifty 50", edgecolor="#3D4260")

    for bar_set in [bars1, bars2]:
        for bar in bar_set:
            h = bar.get_height()
            ax.text(bar.get_x() + bar.get_width() / 2, h + (1 if h >= 0 else -3),
                    f"{h:+.1f}%", ha="center", va="bottom" if h >= 0 else "top",
                    fontsize=7, color=CHART_FG)

    ax.set_xticks(x)
    ax.set_xticklabels(periods)
    ax.set_ylabel("Return (%)", fontsize=9)
    ax.set_title("Historical Returns vs Nifty 50", fontsize=12, fontweight="bold", color=CHART_FG)
    ax.legend(fontsize=8)
    ax.grid(axis="y", alpha=0.3)
    ax.axhline(0, color="#3D4260", linewidth=0.8)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    return _save_chart(fig)


def _make_sensitivity_heatmap(sensitivity_df, cmp):
    _chart_style()
    values = sensitivity_df.values.astype(float)
    values = np.where(np.isinf(values), 0, values)

    fig, ax = plt.subplots(figsize=(6, 4))

    from matplotlib.colors import LinearSegmentedColormap
    cmap = LinearSegmentedColormap.from_list("equilens", [RED, AMBER, ACCENT])

    vmin = cmp * 0.5
    vmax = cmp * 2.0
    im = ax.imshow(values, cmap=cmap, aspect="auto", vmin=vmin, vmax=vmax)

    ax.set_xticks(np.arange(len(sensitivity_df.columns)))
    ax.set_yticks(np.arange(len(sensitivity_df.index)))
    ax.set_xticklabels([str(c) for c in sensitivity_df.columns], fontsize=7)
    ax.set_yticklabels([str(i) for i in sensitivity_df.index], fontsize=7)

    for i in range(len(sensitivity_df.index)):
        for j in range(len(sensitivity_df.columns)):
            v = values[i, j]
            text = f"₹{v:,.0f}" if v > 0 else "N/A"
            text_color = "#000000" if v > cmp else CHART_FG
            ax.text(j, i, text, ha="center", va="center", fontsize=6, color=text_color)

    ax.set_xlabel("Terminal Growth Rate", fontsize=9)
    ax.set_ylabel("WACC", fontsize=9)
    ax.set_title("Sensitivity Analysis: Intrinsic Value", fontsize=12, fontweight="bold", color=CHART_FG)

    plt.colorbar(im, ax=ax, shrink=0.8, label="Intrinsic Value (₹)")

    return _save_chart(fig)


def _make_dcf_waterfall(dcf_result):
    _chart_style()
    pv_fcf = dcf_result.get("sum_pv_fcf", 0) / 1e7
    pv_tv = dcf_result.get("pv_terminal", 0) / 1e7
    debt = dcf_result.get("net_debt", 0) / 1e7
    ev = dcf_result.get("enterprise_value", 0) / 1e7
    eq = dcf_result.get("equity_value", 0) / 1e7

    labels = ["PV of FCFs", "PV of Terminal", "Enterprise Value", "Net Debt Adj.", "Equity Value"]
    values = [pv_fcf, pv_tv, ev, -debt, eq]
    colors = [ACCENT, BLUE, PURPLE, RED, ACCENT]

    fig, ax = plt.subplots(figsize=(6, 3.5))
    bars = ax.bar(labels, values, color=colors, edgecolor="#3D4260", width=0.6)

    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + max(values) * 0.02,
                f"₹{val:,.0f} Cr", ha="center", va="bottom", fontsize=7, color=CHART_FG)

    ax.set_ylabel("Value (₹ Cr)", fontsize=9)
    ax.set_title("DCF Valuation Breakdown", fontsize=12, fontweight="bold", color=CHART_FG)
    ax.grid(axis="y", alpha=0.3)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    plt.xticks(fontsize=7, rotation=15)

    return _save_chart(fig)


def _make_ratio_sparklines(df, title):
    """Small multi-line chart for ratio trends."""
    _chart_style()
    numeric_rows = []
    for idx in df.index:
        vals = df.loc[idx]
        if all(isinstance(v, (int, float, np.floating)) for v in vals):
            numeric_rows.append(idx)

    if not numeric_rows:
        return None

    n = min(len(numeric_rows), 6)
    fig, ax = plt.subplots(figsize=(6, 3))
    colors_cycle = [ACCENT, RED, BLUE, AMBER, PURPLE, PINK]

    for i, ratio_name in enumerate(numeric_rows[:n]):
        vals = df.loc[ratio_name].values.astype(float)
        ax.plot(df.columns.astype(str), vals, marker="o", markersize=4,
                label=ratio_name, color=colors_cycle[i % len(colors_cycle)], linewidth=1.5)

    ax.set_title(title, fontsize=11, fontweight="bold", color=CHART_FG)
    ax.legend(fontsize=6, loc="best", ncol=2)
    ax.grid(alpha=0.3)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    return _save_chart(fig)


# ── Main PDF generation ─────────────────────────────────────────────

def generate_pdf(
    company_name: str,
    ticker: str,
    stock_info: dict,
    all_ratios: dict,
    health_score,
    dcf_result: dict,
    scenarios: dict,
    narrative: str,
    z_score: float,
    z_zone: str,
    assumptions: dict = None,
    comps_result: dict = None,
    rating_result: dict = None,
    shareholding: dict = None,
    hist_returns: dict = None,
    peer_ratios: dict = None,
    sensitivity_df: pd.DataFrame = None,
) -> str:
    pdf = EquiLensPDF(company_name, ticker)
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)

    cmp = stock_info.get("cmp", 0)

    # ── Page 1: Title & Overview ──
    pdf.add_page()

    pdf.set_font("ArialUni", "B", 22)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 15, company_name, align="C")
    pdf.ln(12)
    pdf.set_font("ArialUni", "", 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Ticker: {ticker} | Sector: {stock_info.get('sector', 'N/A')}", align="C")
    pdf.ln(5)
    pdf.cell(0, 8, f"CMP: ₹{cmp:,.2f} | Market Cap: ₹{stock_info.get('market_cap', 0)/1e7:,.0f} Cr", align="C")
    pdf.ln(12)

    # Rating & Target Price
    if rating_result and rating_result.get("rating") != "N/A":
        r = rating_result
        pdf.set_font("ArialUni", "B", 18)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 12, f"Rating: {r['rating']}  |  Target: ₹{r['target_price']:,.0f}  ({r['upside']:+.1f}%)", align="C")
        pdf.ln(8)
        pdf.set_font("ArialUni", "", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, f"Confidence: {r['confidence']} | Methods: {r['methods_used']}", align="C")
        pdf.ln(10)

    # Key Metrics
    pdf.section_title("Key Metrics")
    pdf.key_value("Current Price", f"₹{cmp:,.2f}")
    pdf.key_value("Market Cap", f"₹{stock_info.get('market_cap', 0)/1e7:,.0f} Cr")
    pdf.key_value("P/E Ratio", f"{stock_info.get('pe_ratio', 0):.1f}")
    pdf.key_value("P/B Ratio", f"{stock_info.get('pb_ratio', 0):.1f}")
    pdf.key_value("52-Week Range", f"₹{stock_info.get('52w_low', 0):,.0f} - ₹{stock_info.get('52w_high', 0):,.0f}")
    pdf.key_value("Beta", f"{stock_info.get('beta', 0):.2f}")

    # Health Score with gauge chart
    hs_display = health_score if isinstance(health_score, (int, float)) else health_score.get("score", 0)
    hs_grade = health_score.get("grade", "") if isinstance(health_score, dict) else ""

    try:
        gauge_path = _make_health_gauge(hs_display, hs_grade)
        pdf.add_chart(gauge_path, w=100)
    except Exception:
        grade_str = f" (Grade: {hs_grade})" if hs_grade else ""
        pdf.section_title(f"Financial Health Score: {hs_display}/100{grade_str}")

    pdf.body_text(f"Altman Z-Score: {z_score} ({z_zone} Zone)")

    if isinstance(health_score, dict):
        strengths = health_score.get("strengths", [])
        weaknesses = health_score.get("weaknesses", [])
        if strengths:
            pdf.body_text("Strengths: " + ", ".join(strengths))
        if weaknesses:
            pdf.body_text("Weaknesses: " + ", ".join(weaknesses))

    # ── Page 2: Investment Summary ──
    pdf.add_page()
    pdf.section_title("Investment Summary")
    clean_narrative = narrative.replace("**", "").replace("*", "").replace("₹", "Rs.")
    pdf.body_text(clean_narrative)

    # ── Page 3: DCF Assumptions ──
    if assumptions:
        pdf.add_page()
        pdf.section_title("Auto-Computed DCF Assumptions")
        rationale = assumptions.get("rationale", {})
        pdf.key_value("Revenue Growth", f"{assumptions['revenue_growth']*100:.1f}%")
        if rationale.get("revenue_growth"):
            pdf.body_text(f"  {rationale['revenue_growth']}")
        pdf.key_value("EBITDA Margin", f"{assumptions['ebitda_margin']*100:.1f}%")
        if rationale.get("ebitda_margin"):
            pdf.body_text(f"  {rationale['ebitda_margin']}")
        pdf.key_value("WACC", f"{assumptions['wacc']*100:.1f}%")
        if rationale.get("wacc"):
            pdf.body_text(f"  {rationale['wacc']}")
        pdf.key_value("Terminal Growth", f"{assumptions['terminal_growth']*100:.1f}%")
        if rationale.get("terminal_growth"):
            pdf.body_text(f"  {rationale['terminal_growth']}")
        pdf.key_value("Tax Rate", f"{assumptions['tax_rate']*100:.1f}%")
        pdf.key_value("Capex/Revenue", f"{assumptions['capex_pct']*100:.1f}%")
        pdf.key_value("NWC/Revenue", f"{assumptions['nwc_pct']*100:.1f}%")
        pdf.key_value("D&A/Revenue", f"{assumptions['da_pct']*100:.1f}%")

    # ── Page 4: DCF Valuation ──
    pdf.add_page()
    pdf.section_title("DCF Valuation")
    if dcf_result and dcf_result.get("intrinsic_per_share", 0) > 0:
        pdf.key_value("Intrinsic Value/Share", f"₹{dcf_result['intrinsic_per_share']:,.2f}")
        pdf.key_value("Enterprise Value", f"₹{dcf_result.get('enterprise_value', 0)/1e7:,.0f} Cr")
        pdf.key_value("Equity Value", f"₹{dcf_result.get('equity_value', 0)/1e7:,.0f} Cr")
        pdf.key_value("Sum of PV(FCF)", f"₹{dcf_result.get('sum_pv_fcf', 0)/1e7:,.0f} Cr")
        pdf.key_value("PV(Terminal Value)", f"₹{dcf_result.get('pv_terminal', 0)/1e7:,.0f} Cr")

        upside = ((dcf_result['intrinsic_per_share'] - cmp) / cmp * 100) if cmp > 0 else 0
        pdf.key_value("Upside/Downside vs CMP", f"{upside:+.1f}%")

        # DCF waterfall chart
        try:
            waterfall_path = _make_dcf_waterfall(dcf_result)
            pdf.add_chart(waterfall_path, w=150)
        except Exception:
            pass

        # Projected FCFs
        proj = dcf_result.get("projections")
        if proj is not None and not proj.empty:
            pdf.ln(3)
            pdf.sub_title("Projected Free Cash Flows")
            headers = list(proj.columns)
            rows = []
            for _, row in proj.iterrows():
                r = []
                for col in headers:
                    val = row[col]
                    if col == "Year":
                        r.append(str(int(val)))
                    elif isinstance(val, (int, float)):
                        r.append(f"₹{val/1e7:,.0f} Cr")
                    else:
                        r.append(str(val))
                rows.append(r)
            pdf.add_simple_table(headers, rows)
    else:
        pdf.body_text("DCF not applicable for this company (e.g., financial services sector).")

    # Scenarios with chart
    if scenarios:
        pdf.sub_title("Scenario Analysis")
        try:
            scenario_path = _make_scenario_chart(scenarios, cmp)
            pdf.add_chart(scenario_path, w=140)
        except Exception:
            for name, val in scenarios.items():
                upside_s = ((val - cmp) / cmp * 100) if cmp > 0 else 0
                pdf.key_value(f"{name} Case", f"₹{val:,.0f} ({upside_s:+.1f}%)")

    # ── Page 5: Comparable Valuation ──
    if comps_result:
        pe = comps_result.get("pe_comps", {})
        ev = comps_result.get("ev_ebitda_comps", {})
        if pe.get("applicable") or ev.get("applicable"):
            pdf.add_page()
            pdf.section_title("Comparable Valuation")
            if pe.get("applicable"):
                pdf.sub_title("P/E Comps")
                pdf.key_value("Target EPS", f"₹{pe.get('target_eps', 0):.2f}")
                pdf.key_value("Peer Median PE", f"{pe['peer_median_pe']:.1f}x")
                pdf.key_value("Fair Value (Median)", f"₹{pe['fair_value_median']:,.0f}")
                pdf.key_value("Fair Value Range", f"₹{pe['fair_value_low']:,.0f} - ₹{pe['fair_value_high']:,.0f}")
            if ev.get("applicable"):
                pdf.sub_title("EV/EBITDA Comps")
                pdf.key_value("Peer Median Multiple", f"{ev['peer_median_multiple']:.1f}x")
                pdf.key_value("Fair Value (Median)", f"₹{ev['fair_value_median']:,.0f}")
                pdf.key_value("Fair Value Range", f"₹{ev['fair_value_low']:,.0f} - ₹{ev['fair_value_high']:,.0f}")

    # ── Page 6: Sensitivity Analysis with heatmap ──
    if sensitivity_df is not None and not sensitivity_df.empty:
        pdf.add_page()
        pdf.section_title("Sensitivity Analysis (WACC vs Terminal Growth)")

        try:
            heatmap_path = _make_sensitivity_heatmap(sensitivity_df, cmp)
            pdf.add_chart(heatmap_path, w=160)
        except Exception:
            pass

        pdf.ln(3)
        headers = ["WACC \\ TGR"] + list(sensitivity_df.columns)
        rows = []
        for idx in sensitivity_df.index:
            row = [str(idx)]
            for col in sensitivity_df.columns:
                val = sensitivity_df.loc[idx, col]
                if isinstance(val, (int, float)) and not np.isinf(val) and val > 0:
                    row.append(f"₹{val:,.0f}")
                else:
                    row.append("N/A")
            rows.append(row)
        pdf.add_simple_table(headers, rows)

    # ── Ratio Pages with trend charts ──
    ratio_order = [
        ("liquidity", "Liquidity Ratios"),
        ("profitability", "Profitability Ratios"),
        ("efficiency", "Efficiency Ratios"),
        ("solvency", "Solvency Ratios"),
        ("dupont", "DuPont Decomposition"),
        ("altman", "Altman Z-Score Components"),
    ]
    for category, title in ratio_order:
        df = all_ratios.get(category, pd.DataFrame())
        if isinstance(df, pd.DataFrame) and not df.empty:
            pdf.add_page()
            pdf.add_ratio_table(title, df)

            try:
                chart_path = _make_ratio_sparklines(df, f"{title} — Trend")
                if chart_path:
                    pdf.add_chart(chart_path, w=150)
            except Exception:
                pass

    # ── Peer Comparison ──
    if peer_ratios and len(peer_ratios) > 1:
        pdf.add_page()
        pdf.section_title("Peer Comparison")
        comp_df = pd.DataFrame(peer_ratios).T
        comp_df.index = [t.replace(".NS", "") for t in comp_df.index]
        numeric_cols = comp_df.select_dtypes(include=[np.number]).columns.tolist()
        if numeric_cols:
            display_df = comp_df[numeric_cols].round(2)
            pdf.add_ratio_table("Peer Ratios", display_df.T)

    # ── Shareholding Pattern with donut chart ──
    if shareholding and any(v > 0 for v in shareholding.values()):
        pdf.add_page()
        pdf.section_title("Shareholding Pattern")

        try:
            donut_path = _make_shareholding_chart(shareholding)
            if donut_path:
                pdf.add_chart(donut_path, w=110)
        except Exception:
            pass

        for holder, pct in shareholding.items():
            if pct > 0:
                pdf.key_value(holder, f"{pct:.1f}%")

    # ── Historical Returns with chart ──
    if hist_returns and any(d.get("stock") is not None for d in hist_returns.values()):
        pdf.ln(5)
        pdf.section_title("Historical Returns vs Nifty 50")

        try:
            returns_path = _make_returns_chart(hist_returns, ticker)
            if returns_path:
                pdf.add_chart(returns_path, w=130)
        except Exception:
            pass

        headers = ["Period", "Stock Return", "Nifty 50 Return"]
        rows = []
        for period in ["1Y", "3Y", "5Y"]:
            data = hist_returns.get(period, {})
            s = data.get("stock")
            b = data.get("benchmark")
            if s is not None:
                rows.append([
                    period,
                    f"{s:+.1f}%",
                    f"{b:+.1f}%" if b is not None else "N/A",
                ])
        if rows:
            pdf.add_simple_table(headers, rows)

    # ── Traffic Light Dashboard ──
    pdf.add_page()
    pdf.section_title("Traffic Light Dashboard")
    headers = ["Category", "Ratio", "Value", "Signal"]
    rows = []
    for category, df in all_ratios.items():
        if not isinstance(df, pd.DataFrame) or df.empty:
            continue
        latest_yr = df.columns[-1]
        for ratio_name in df.index:
            val = df.loc[ratio_name, latest_yr]
            if not isinstance(val, (int, float)):
                continue
            from ratio_engine import get_traffic_light
            light = get_traffic_light(ratio_name, val, stock_info.get("sector", ""))
            signal = {"green": "Good", "amber": "Watch", "red": "Concern"}.get(light, "-")
            rows.append([category.title(), ratio_name, f"{val:.2f}", signal])
    if rows:
        pdf.add_simple_table(headers, rows)

    # ── Disclaimer ──
    pdf.add_page()
    pdf.section_title("Disclaimer")
    pdf.body_text(
        "This report is generated automatically by EquiLens for educational and informational purposes only. "
        "It does not constitute investment advice. Always consult a SEBI-registered investment advisor "
        "before making investment decisions. Past performance is not indicative of future results. "
        "The data used in this report is sourced from public APIs and may contain errors or delays."
    )

    # Save to temp file
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf", prefix=f"EquiLens_{ticker}_")
    pdf.output(tmp.name)
    pdf.cleanup()
    return tmp.name
